Portfolyo/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Portfolyo.Controllers
{
    public class SkillController : Controller
    {
        SkillManager _skillManager = new(new EfSkillDal());

        [HttpGet("/Skill/")]
        public IActionResult Index()
        {
            ViewBag.v1 = "Yetenek Listeleme Sayfası";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Listeleme";
            var values = _skillManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.v1 = "Yetenek Listeleme Sayfası";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Ekleme";
            return View();
        }

        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            _skillManager.TAdd(skill);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DeleteSkill(int id)
        {
            var skill = _skillManager.TGetById(id);
            _skillManager.TDelete(skill);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            ViewBag.v1 = "Yetenek Listeleme Sayfası";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenekler Güncelleme";
            var skill = _skillManager.TGetById(id);
            return View(skill);
        }

        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            _skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }
    }
}

Portfolyo/Views/Skill/AddSkill.cshtml
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using EntityLayer.Concrete;

@model Skill

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description">Yetenek Ekleme Paneli</p>
            @using (Html.BeginForm("AddSkill", "Skill", FormMethod.Post, new { @class = "forms-sample"}))
            {
                <div class="form-group">
                    <label>Başlık</label>
                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                </div>
                <br />
                <div class="form-group">
                    <label>Değer</label>
                    @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                </div>
                <br />
                <button type="submit" class="btn btn-primary mr-2">Ekle</button>
                <a class="btn btn-dark" href="/Skill">İptal</a>
            }
        </div>
    </div>
</div>

Portfolyo/Views/Skill/EditSkill.cshtml
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@model EntityLayer.Concrete.Skill

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description">Yetenek Düzenleme Paneli</p>
            @using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post, new { @class = "forms-sample"}))
            {
                <div class="form-group">
                    @Html.HiddenFor(x => x.SkillID, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Başlık</label>
                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                </div>
                <br />
                <div class="form-group">
                    <label>Değer</label>
                    @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                </div>
                <br />
                <button type="submit" class="btn btn-success mr-2">Güncelle</button>
                <a class="btn btn-dark" href="/Skill">İptal</a>
            }
        </div>
    </div>
</div>

Portfolyo/Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill> 

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Oran</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>
                                    @item.SkillID
                                </th>
                                <td class="budget">
                                    @item.Title
                                </td>
                               <td>
                                    <div class="d-flex align-items-center">
                                        <span class="completion mr-2">@item.Value</span>
                                        <div>
                                            <div class="progress">
                                                <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td><a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-danger">Sil</a></td>
                                <td><a href="/Skill/EditSkill/@item.SkillID" class="btn btn-info">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a href="/Skill/AddSkill" class="btn btn-outline-info">Yeni Yetenek Ekle</a>
            </div>
        </div>
    </div>
</div>