Portfolyo/Controllers/ExperienceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Portfolyo.Controllers
{
    public class ExperienceController : Controller
    {
        ExperienceManager _experienceManager = new(new EfExperienceDal());

        [HttpGet("/Experience/")]
        public IActionResult Index()
        {
            ViewBag.v1 = "Deneyimler Sayfası";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Listesi";
            var experiences = _experienceManager.TGetList();
            return View(experiences);
        }

        [HttpGet]
        public IActionResult AddExperience()
        {
            ViewBag.v1 = "Deneyimler Sayfası";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Ekleme";
            return View();
        }

        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            _experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DeleteExperience(int id)
        {
            var experience = _experienceManager.TGetById(id);
            if (experience == null)
                // TODO: Redirect to error page
                return RedirectToAction("Index");
            _experienceManager.TDelete(experience);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditExperience(int id)
        {
            ViewBag.v1 = "Deneyimler Sayfası";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Güncelleme";
            var result = _experienceManager.TGetById(id);
            if (result == null)
                // TODO: Redirect to error page
                return RedirectToAction("Index");
            return View(result);
        }

        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            var result = _experienceManager.TGetById(experience.ExperienceID);
            if (result == null)
                // TODO: Redirect to error page
                return RedirectToAction("Index");
            _experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

Portfolyo/Views/Experience/AddExperience.cshtml
@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using EntityLayer.Concrete;

@model Experience

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description"> Yeni Deneyim Ekleme Paneli </p>
            @using(Html.BeginForm("AddExperience", "Experience", FormMethod.Post, new { @class = "forms-sample"}))
            {
                <div class="form-group">
                    <label>Başlık</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Tarih</label>
                    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Görsel URL</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Açıklama</label>
                    @Html.TextAreaFor(x => x.Description, 6, 3, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-primary mr-2">Ekle</button>
                <a class="btn btn-dark" href="/Experience">İptal</a>
            }
        </div>
    </div>
</div>

Portfolyo/Views/Experience/EditExperience.cshtml
@{
    ViewData["Title"] = "EditExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using EntityLayer.Concrete;

@model Experience

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description"> Yeni Deneyim Ekleme Paneli </p>
            @using(Html.BeginForm("EditExperience", "Experience", FormMethod.Post, new { @class = "forms-sample"}))
            {
                @Html.HiddenFor(x => x.ExperienceID, new { @class = "form-control" })
                <div class="form-group">
                    <label>Başlık</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Tarih</label>
                    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Görsel URL</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Açıklama</label>
                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-primary mr-2">Güncelle</button>
                <a class="btn btn-dark" href="/Experience">İptal</a>
            }
        </div>
    </div>
</div>

Portfolyo/Views/Experience/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using EntityLayer.Concrete;

@model List<Experience>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Tarih</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                            <tr>
                                <td>@item.ExperienceID</td>
                                <td>@item.Name</td>
                                <td>@item.Date</td>
                                <td><a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-outline-danger">Sil</a></td>
                                <td><a href="/Experience/EditExperience/@item.ExperienceID" class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a href="/Experience/AddExperience" class="btn btn-outline-info">Yeni Deneyim Ekle</a>
            </div>
        </div>
    </div>
</div>